language: java
jdk :
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/DoIt_BE.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-build
    region: ap-northeast-2
    cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true
    on:
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-build
    key: DoIt_BE.zip
    bundle_type: zip
    application: travis-deploy
    deployment_group: travis-webservice-group
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      branch: master


notifications:
  email:
    recipients:
      - hyotaek9812@gmail.com
      - gkwls1130@ajou.ac.kr