language: java
jdk :
  - openjdk11

branches:
  only:
    - master
    - develop

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r DoIt_BE *
  - mkdir -p deploy
  - mv DoIt_BE.zip deploy/DoIt_BE.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: develop
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-build
    key: DoIt_BE.zip
    bundle_type: zip
    application: travis-deploy
    deployment_group: travis-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: develop


notifications:
  email:
    recipients:
      - hyotaek9812@gmail.com
